version: '2'
services:
  dbpedia-spotlight:
    image: librairy/dbpedia-en:latest
  nlp-en-service:
    image: librairy/nlp-en-service:latest
  learner:
    image: librairy/learner-topics-service:latest
    ports:
     - "8080:7777"
    environment:
     - LIBRAIRY_API_USERS=learner:oeg2018
    volumes:
     - .:/librairy
     - /var/run/docker.sock:/var/run/docker.sock
